on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config-staging.json
