name: release-please

on:
    push:
        branches:
            - staging

permissions: read-all # We do not use workflow permissions, instead we use techsharebot's PAT

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
